services:
  mongo:
    image: mongo:5.0.1
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo
    volumes:
      - data:/data # маппим volumes на хосте с /data в контейнере
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    restart: always
    networks:
      - mongo

volumes:
  data: {} # volumes на хосте

networks:
  mongo:
    name: mongo

